services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx sequelize-cli db:migrate --config src/config/sequelize/config.js --migrations-path src/migrations --models-path src/models && node src/index.js"
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx sequelize-cli db:migrate --config src/config/sequelize/config.js --migrations-path src/migrations --models-path src/models && npm test"
    volumes:
      - .:/app

volumes:
  db_data:
